[package]
name = "darkpool_program"
version = "0.1.0"
edition = "2024"

[dependencies]
web3 = "0.19.0"
solana-cli = "3.0.8"
tracing = "0.1.41"
anyhow = "1.0.100"
postgres = "0.19.12"
anchor-lang = { version = "0.32.1", features = ["derive"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
